repos:
  # --- Ruff ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3            # pin to the latest stable tag
    hooks:
      - id: ruff
        # Auto-fix everything Ruff can, including “unsafe-fixes”
        args: [--fix, --unsafe-fixes]

  # --- Black ---
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  # --- Pyupgrade ---
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade