name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install spaCy model and NLTK data
        run: |
          python -m spacy download en_core_web_sm
          python -c "import nltk; nltk.download('punkt'); nltk.download('punkt_tab'); nltk.download('stopwords'); nltk.download('wordnet')"
      - name: Lint & Type Check
        run: |
          ruff check .
          python -m compileall -q legal_parser
      - name: Run Tests
        run: |
          pytest -q --asyncio-mode=strict --timeout=60 --cov=legal_parser